### 폐암 수술 환자 생존율 예측 딥러닝

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
np.random.seed(3)
tf.random.set_seed(3)

In [4]:
Data_set = np.loadtxt('dataset/ThoraricSurgery.csv', delimiter=',')
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [5]:
X = Data_set[:,0:17]
Y = Data_set[:, 17]

In [6]:
X

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [7]:
Y

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [8]:
print('X shape:',np.shape(X))
print('Y shape:',np.shape(Y))

X shape: (470, 17)
Y shape: (470,)


In [9]:
model = Sequential()
model.add(Dense(30, input_dim=17, activation='relu'))  # input_dim : X 데이터 17가지 노드 17개로 입력
model.add(Dense(1, activation='sigmoid'))

In [10]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

Train on 470 samples
Epoch 1/100
470/470 [==============================] - 1s 2ms/sample - loss: 0.6902 - accuracy: 0.8106
Epoch 2/100
470/470 [==============================] - 0s 110us/sample - loss: 0.4568 - accuracy: 0.8511
Epoch 3/100
470/470 [==============================] - 0s 82us/sample - loss: 0.4714 - accuracy: 0.8447
Epoch 4/100
470/470 [==============================] - 0s 106us/sample - loss: 0.4609 - accuracy: 0.8447
Epoch 5/100
470/470 [==============================] - 0s 108us/sample - loss: 0.4535 - accuracy: 0.8511
Epoch 6/100
470/470 [==============================] - 0s 147us/sample - loss: 0.4576 - accuracy: 0.8532
Epoch 7/100
470/470 [==============================] - 0s 171us/sample - loss: 0.4410 - accuracy: 0.8511
Epoch 8/100
470/470 [==============================] - 0s 156us/sample - loss: 0.4306 - accuracy: 0.8511
Epoch 9/100
470/470 [==============================] - 0s 126us/sample - loss: 0.4469 - accuracy: 0.8511
Epoch 10/100
470/470 [===============