### 폐암 수술 환자 생존율 예측 딥러닝
#### sklearn 이용한 학습 데이터와 테스트 데이터 분리 (7:3)

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np
import tensorflow as tf

In [4]:
np.random.seed(3)
tf.random.set_seed(3)

In [5]:
Data_set = np.loadtxt('dataset/ThoraricSurgery.csv', delimiter=',')
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [6]:
X = Data_set[:,0:17]
Y = Data_set[:, 17]

In [7]:
X

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [8]:
Y

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [9]:
print('X shape:',np.shape(X))
print('Y shape:',np.shape(Y))

X shape: (470, 17)
Y shape: (470,)


In [10]:
seed = 0
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state= seed)

In [11]:
print(len(X_train))
print(len(X_test))

329
141


In [12]:
model = Sequential()
model.add(Dense(30, input_dim=17, activation='relu'))  # input_dim : X 데이터 17가지 노드 17개로 입력
model.add(Dense(1, activation='sigmoid'))

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=100, batch_size=10)

Train on 329 samples
Epoch 1/100
329/329 [==============================] - 2s 5ms/sample - loss: 0.9772 - accuracy: 0.7447
Epoch 2/100
329/329 [==============================] - 0s 239us/sample - loss: 0.4976 - accuracy: 0.8359
Epoch 3/100
329/329 [==============================] - 0s 267us/sample - loss: 0.4779 - accuracy: 0.8359
Epoch 4/100
329/329 [==============================] - 0s 112us/sample - loss: 0.4743 - accuracy: 0.8116
Epoch 5/100
329/329 [==============================] - 0s 194us/sample - loss: 0.4826 - accuracy: 0.8328
Epoch 6/100
329/329 [==============================] - 0s 273us/sample - loss: 0.4546 - accuracy: 0.8359
Epoch 7/100
329/329 [==============================] - 0s 282us/sample - loss: 0.4638 - accuracy: 0.8359
Epoch 8/100
329/329 [==============================] - 0s 517us/sample - loss: 0.4579 - accuracy: 0.8298
Epoch 9/100
329/329 [==============================] - 0s 160us/sample - loss: 0.4447 - accuracy: 0.8298
Epoch 10/100
329/329 [==============

Epoch 78/100
329/329 [==============================] - 0s 218us/sample - loss: 0.4341 - accuracy: 0.8389
Epoch 79/100
329/329 [==============================] - 0s 136us/sample - loss: 0.4025 - accuracy: 0.8450
Epoch 80/100
329/329 [==============================] - 0s 158us/sample - loss: 0.4420 - accuracy: 0.8176
Epoch 81/100
329/329 [==============================] - 0s 309us/sample - loss: 0.4143 - accuracy: 0.8511
Epoch 82/100
329/329 [==============================] - 0s 300us/sample - loss: 0.4105 - accuracy: 0.8480
Epoch 83/100
329/329 [==============================] - 0s 267us/sample - loss: 0.4194 - accuracy: 0.8389
Epoch 84/100
329/329 [==============================] - 0s 200us/sample - loss: 0.4101 - accuracy: 0.8419
Epoch 85/100
329/329 [==============================] - 0s 88us/sample - loss: 0.4155 - accuracy: 0.8450
Epoch 86/100
329/329 [==============================] - 0s 91us/sample - loss: 0.4501 - accuracy: 0.8146
Epoch 87/100
329/329 [==========================

In [14]:
model.evaluate(X_test, Y_test)  # 학습으로 구한 weight를 테스트에 적용

141/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.4981197938851431, 0.8652482]

#### 학습 후 예측

In [15]:
kim = np.array([[293,1,3.8,2.8,0,0,0,0,0,0,12,0,0,0,1,0,62]])
print(model.predict(kim))

[[0.03467136]]


In [16]:
test_kim = model.predict(kim)*100
print('백분율로 표시 :', test_kim)
print('Kim 폐암 수술 후 생존율 예측 : %.2f' %test_kim, "%")

백분율로 표시 : [[3.4671354]]
Kim 폐암 수술 후 생존율 예측 : 3.47 %


In [17]:
park = np.array([[197,3,2.84,2.24,1,1,1,0,0,0,12,0,0,0,1,0,68]])
print(model.predict(park))

[[0.10510628]]


In [18]:
test_park = model.predict(park)*100
print('백분율로 표시 :', test_park)
print('Park 폐암 수술 후 생존율 예측 : %.2f' %test_park, "%")

백분율로 표시 : [[10.510628]]
Park 폐암 수술 후 생존율 예측 : 10.51 %


In [19]:
model.save('ThoraricSurgery_deeplearning_result.h5')