In [1]:
import sys

In [2]:
print(sys.version)

3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]


In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import tensorflow as tf

In [2]:
np.random.seed(3)

In [4]:
tf.random.set_seed(3)

In [5]:
Data_set = np.loadtxt('C:/ai/2021_AI/dataset/ThoraricSurgery.csv', delimiter=',')

In [6]:
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [7]:
type(Data_set)

numpy.ndarray

In [8]:
X = Data_set[:, 0:17]
X

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [9]:
Y = Data_set[:, 17]
Y

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [10]:
model = Sequential()
model

In [11]:
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [12]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

Train on 470 samples
Epoch 1/100
470/470 [==============================] - 1s 1ms/sample - loss: 0.6902 - accuracy: 0.8106
Epoch 2/100
470/470 [==============================] - 0s 149us/sample - loss: 0.4568 - accuracy: 0.8511
Epoch 3/100
470/470 [==============================] - 0s 183us/sample - loss: 0.4714 - accuracy: 0.8447
Epoch 4/100
470/470 [==============================] - 0s 199us/sample - loss: 0.4609 - accuracy: 0.8447
Epoch 5/100
470/470 [==============================] - 0s 164us/sample - loss: 0.4535 - accuracy: 0.8511
Epoch 6/100
470/470 [==============================] - 0s 153us/sample - loss: 0.4576 - accuracy: 0.8532
Epoch 7/100
470/470 [==============================] - 0s 156us/sample - loss: 0.4410 - accuracy: 0.8511
Epoch 8/100
470/470 [==============================] - 0s 124us/sample - loss: 0.4306 - accuracy: 0.8511
Epoch 9/100
470/470 [==============================] - 0s 123us/sample - loss: 0.4469 - accuracy: 0.8511
Epoch 10/100
470/470 [==============

470/470 [==============================] - 0s 162us/sample - loss: 0.3807 - accuracy: 0.8596
Epoch 78/100
470/470 [==============================] - 0s 165us/sample - loss: 0.4029 - accuracy: 0.8511
Epoch 79/100
470/470 [==============================] - 0s 155us/sample - loss: 0.4004 - accuracy: 0.8426
Epoch 80/100
470/470 [==============================] - 0s 171us/sample - loss: 0.4070 - accuracy: 0.8468
Epoch 81/100
470/470 [==============================] - 0s 177us/sample - loss: 0.3829 - accuracy: 0.8596
Epoch 82/100
470/470 [==============================] - 0s 168us/sample - loss: 0.3990 - accuracy: 0.8489
Epoch 83/100
470/470 [==============================] - 0s 207us/sample - loss: 0.4090 - accuracy: 0.8532
Epoch 84/100
470/470 [==============================] - 0s 173us/sample - loss: 0.4089 - accuracy: 0.8362
Epoch 85/100
470/470 [==============================] - 0s 110us/sample - loss: 0.4268 - accuracy: 0.8404
Epoch 86/100
470/470 [==============================] - 0s 

In [13]:
new_x = np.array([[293,1,3.8,2.8,0,0,0,0,0,0,12,0,0,0,1,0,62]])
y_predict = model.predict(new_x)
print(y_predict)

[[0.0943418]]


In [14]:
new_x = np.array([[197,3,2.84,2.24,1,1,1,0,0,0,12,0,0,0,1,0,68]])
y_predict = model.predict(new_x)
print(y_predict)

[[0.23978588]]


In [15]:
from keras.models import load_model

model.save('my_model.h5')

Using TensorFlow backend.
